# tickstream AWS foundation. Backend configured via infra/backend.hcl
# (generated by `make infra-bootstrap`). Plan: `make infra-plan`. Apply: approved only.

terraform {
  required_version = ">= 1.9.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      Project   = var.project
      ManagedBy = "opentofu"
    }
  }
}

data "aws_caller_identity" "current" {}
